export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const SET_INGREDIENTS = 'SET_INGREDIENTS';
//export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';