//Builder
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';

//Orders
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_FIN = 'PURCHASE_FIN';

export const FETCH_ORDERS_START= 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS= 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED= 'FETCH_ORDERS_FAILED';

//Auth
export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS ';
export const AUTH_FAILED= 'AUTH_FAILED';