/* =Builder= */
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';

/* =Orders= */
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_FIN = 'PURCHASE_FIN';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

/* =Auth= */
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS ';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

/*=Menu=*/
export const MENU_FETCH_START = 'MENU_FETCH_START';
export const MENU_FETCH_SUCCESS = 'MENU_FETCH_SUCCESS';
export const MENU_FETCH_FAILED = 'MENU_FETCH_FAILED';
export const MENU_PUSH_START = 'MENU_PUSH_START';
export const MENU_PUSH_FAILED = 'MENU_PUSH_FAILED';
export const MENU_PUSH_SUCCESS = 'MENU_PUSH_SUCCESS';
export const MENU_PATCH_START = 'MENU_PATCH_START';
export const MENU_PATCH_FAILED = 'MENU_PATCH_FAILED';
export const MENU_PATCH_SUCCESS= 'MENU_PATCH_SUCCESS';